version: "3"
services:
  server:
    image: spring-app-backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employee_schema?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee_schema
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

networks:
  springmysql-net: